# Retrieving audiovisual works derived from written works from Wikidata

In [3]:
from pandas import *
from queryWikidata import query_wikidata

In [4]:
endpoint = "https://query.wikidata.org/sparql"
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0"

## 1. Audiovisual works and written works

In [27]:
derivative_works = set()

In [28]:
q1_based_on = """
SELECT DISTINCT ?derivativeWork
WHERE {
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
    ?derivativeWork wdt:P31/wdt:P279* wd:Q2431196  .
    ?derivativeWork wdt:P144 ?work .                           
} 
"""
based_on_df1 = query_wikidata(endpoint, q1_based_on, user_agent, True)

# Add the results to the set
for index, row in based_on_df1.iterrows():
    derivative_works.add(row['derivativeWork'])
    
based_on_df1

                                 derivativeWork
0        http://www.wikidata.org/entity/Q520744
1        http://www.wikidata.org/entity/Q601760
2        http://www.wikidata.org/entity/Q184542
3       http://www.wikidata.org/entity/Q3079966
4        http://www.wikidata.org/entity/Q745283
...                                         ...
14936  http://www.wikidata.org/entity/Q25454430
14937  http://www.wikidata.org/entity/Q27964343
14938  http://www.wikidata.org/entity/Q28730407
14939  http://www.wikidata.org/entity/Q48856206
14940  http://www.wikidata.org/entity/Q57523564

[14941 rows x 1 columns]

In [29]:
q1_influenced_by = """
SELECT DISTINCT ?derivativeWork
WHERE {
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
    ?derivativeWork wdt:P31/wdt:P279* wd:Q2431196  .
    ?derivativeWork wdt:P737 ?work .                           
} 
"""
influenced_by_df1 = query_wikidata(endpoint, q1_influenced_by, user_agent, True)

# Add the results to the set
for index, row in influenced_by_df1.iterrows():
    derivative_works.add(row['derivativeWork'])

influenced_by_df1

                               derivativeWork
0    http://www.wikidata.org/entity/Q65738708
1      http://www.wikidata.org/entity/Q337881
2      http://www.wikidata.org/entity/Q488655
3      http://www.wikidata.org/entity/Q696455
4     http://www.wikidata.org/entity/Q1218888
5     http://www.wikidata.org/entity/Q1545458
6     http://www.wikidata.org/entity/Q3824799
7     http://www.wikidata.org/entity/Q4424338
8    http://www.wikidata.org/entity/Q46034734
9   http://www.wikidata.org/entity/Q109828410
10       http://www.wikidata.org/entity/Q2744

In [30]:
q1_inspired_by = """
SELECT DISTINCT ?derivativeWork
WHERE {
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
    ?derivativeWork wdt:P31/wdt:P279* wd:Q2431196  .
    ?derivativeWork wdt:P941 ?work .                           
} 
"""
inspired_by_df1 = query_wikidata(endpoint, q1_inspired_by, user_agent, True)

# Add the results to the set
for index, row in inspired_by_df1.iterrows():
    derivative_works.add(row['derivativeWork'])

inspired_by_df1

                               derivativeWork
0     http://www.wikidata.org/entity/Q3829154
1     http://www.wikidata.org/entity/Q1196184
2     http://www.wikidata.org/entity/Q7728885
3    http://www.wikidata.org/entity/Q16688763
4    http://www.wikidata.org/entity/Q10526473
..                                        ...
260   http://www.wikidata.org/entity/Q6651529
261  http://www.wikidata.org/entity/Q12125766
262  http://www.wikidata.org/entity/Q15865201
263   http://www.wikidata.org/entity/Q2027855
264    http://www.wikidata.org/entity/Q177233

[265 rows x 1 columns]

In [31]:
q1_reference = """
SELECT DISTINCT ?derivativeWork
WHERE {
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
    ?derivativeWork wdt:P31/wdt:P279* wd:Q2431196  .
    ?derivativeWork wdt:P8371 ?work .                           
} 
"""
reference_df1 = query_wikidata(endpoint, q1_reference, user_agent, True)

# Add the results to the set
for index, row in reference_df1.iterrows():
    derivative_works.add(row['derivativeWork'])

reference_df1

                              derivativeWork
0      http://www.wikidata.org/entity/Q74401
1    http://www.wikidata.org/entity/Q1529879
2    http://www.wikidata.org/entity/Q8028590
3     http://www.wikidata.org/entity/Q318975
4    http://www.wikidata.org/entity/Q3232629
..                                       ...
84  http://www.wikidata.org/entity/Q16744121
85    http://www.wikidata.org/entity/Q200572
86   http://www.wikidata.org/entity/Q6950089
87  http://www.wikidata.org/entity/Q64577280
88   http://www.wikidata.org/entity/Q1689499

[89 rows x 1 columns]

In [32]:
q1_derived = """
SELECT DISTINCT ?derivativeWork 
WHERE {
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
    ?derivativeWork wdt:P31/wdt:P279* wd:Q2431196  .
    ?derivativeWork wdt:P4969 ?work .                           
} 
"""
derived_df1 = query_wikidata(endpoint, q1_derived, user_agent, True)

# Add the results to the set
for index, row in derived_df1.iterrows():
    derivative_works.add(row['derivativeWork'])

derived_df1

                              derivativeWork
0     http://www.wikidata.org/entity/Q131007
1     http://www.wikidata.org/entity/Q108774
2     http://www.wikidata.org/entity/Q212156
3     http://www.wikidata.org/entity/Q622282
4     http://www.wikidata.org/entity/Q171711
..                                       ...
283  http://www.wikidata.org/entity/Q1247268
284  http://www.wikidata.org/entity/Q1247482
285  http://www.wikidata.org/entity/Q1247488
286  http://www.wikidata.org/entity/Q3285246
287   http://www.wikidata.org/entity/Q390120

[288 rows x 1 columns]

In [33]:
q1_inspired_by_artist = """
SELECT DISTINCT ?derivativeWork
WHERE {
    {
      ?work wdt:P170 ?person .
     }UNION{
      ?work wdt:P50 ?person .                           
     }UNION{
      VALUES ?authorOf {wdt:P1455 wdt:P800}      
      ?person ?authorOf ?work .
    }
  
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
    
    ?derivativeWork wdt:P31/wdt:P279* wd:Q2431196  .
    ?derivativeWork wdt:P1877 ?person .                         
} 
"""
inspired_by_artist_df1 = query_wikidata(endpoint, q1_inspired_by_artist, user_agent, True)

for index, row in inspired_by_artist_df1.iterrows():
    derivative_works.add(row['derivativeWork'])

inspired_by_artist_df1

                                 derivativeWork
0        http://www.wikidata.org/entity/Q293219
1        http://www.wikidata.org/entity/Q133504
2        http://www.wikidata.org/entity/Q181221
3        http://www.wikidata.org/entity/Q181242
4        http://www.wikidata.org/entity/Q139684
...                                         ...
5875  http://www.wikidata.org/entity/Q111262699
5876  http://www.wikidata.org/entity/Q110883204
5877   http://www.wikidata.org/entity/Q10514660
5878   http://www.wikidata.org/entity/Q97142447
5879     http://www.wikidata.org/entity/Q808114

[5880 rows x 1 columns]

In [34]:
len(derivative_works)

16496

### b. Audiovisual works and Italian written works

In [35]:
derived_works_iww = set()

In [36]:
based_on_italian_ww = """
SELECT DISTINCT ?derivativeWork
WHERE {
  {
    ?work wdt:P31 wd:Q47461344 .
  }UNION{
    ?work wdt:P31/wdt:P279* wd:Q7725634 .
  }
  ?derivativeWork wdt:P31/wdt:P279* wd:Q2431196  .
  ?derivativeWork wdt:P144 ?work .

  ?person wdt:P31 wd:Q5 ;
            wdt:P27 ?country .                          #the block gets the writers having had the citizenship of a country, whose capital city is now an Italian city
  ?country (wdt:P36 | p:P36 / ps:P36) ?capitalCity .  
  ?capitalCity wdt:P31 wd:Q515 ; #get cities
                  wdt:P17 wd:Q38 .


    {
      ?work wdt:P170 ?person .
     }UNION{
      ?work wdt:P50 ?person .                            
     }UNION{
      VALUES ?authorOf {wdt:P1455 wdt:P800}      
      ?person ?authorOf ?work .
    }

} 
"""
based_on_iww_df = query_wikidata(endpoint, based_on_italian_ww, user_agent, True)

# Add the results to the set
for index, row in based_on_iww_df.iterrows():
    derived_works_iww.add(row['derivativeWork'])

based_on_iww_df

                                derivativeWork
0     http://www.wikidata.org/entity/Q28214950
1      http://www.wikidata.org/entity/Q3441137
2      http://www.wikidata.org/entity/Q3655400
3      http://www.wikidata.org/entity/Q3791031
4      http://www.wikidata.org/entity/Q3793051
..                                         ...
244  http://www.wikidata.org/entity/Q110931235
245   http://www.wikidata.org/entity/Q59348694
246   http://www.wikidata.org/entity/Q88787767
247    http://www.wikidata.org/entity/Q3533342
248    http://www.wikidata.org/entity/Q3950747

[249 rows x 1 columns]

In [37]:
based_on_italian_ww2 = """
SELECT DISTINCT ?derivativeWork
WHERE {
  {
    ?work wdt:P31 wd:Q47461344 .
  }UNION{
    ?work wdt:P31/wdt:P279* wd:Q7725634 .
  }
  ?derivativeWork wdt:P31/wdt:P279* wd:Q2431196  .
  ?derivativeWork wdt:P144 ?work .
  
  ?work wdt:P407 wd:Q652 .
  
  MINUS {
     {
      ?work wdt:P170 ?person .
     }UNION{
      ?work wdt:P50 ?person .                            
     }UNION{
      VALUES ?authorOf {wdt:P1455 wdt:P800}      
      ?person ?authorOf ?work .
    }
  ?person wdt:P31 wd:Q5 ;
            wdt:P27 ?country .                          #the block gets the writers having had the citizenship of a country, whose capital city is now an Italian city
  ?country (wdt:P36 | p:P36 / ps:P36) ?capitalCity .  
  ?capitalCity wdt:P31 wd:Q515 . #get cities
  FILTER NOT EXISTS { ?capitalCity wdt:P17 wd:Q38 . }
  }

} 
"""
based_on_iww_df2 = query_wikidata(endpoint, based_on_italian_ww2, user_agent, True)

# Add the results to the set
for index, row in based_on_iww_df2.iterrows():
    derived_works_iww.add(row['derivativeWork'])

based_on_iww_df2

                               derivativeWork
0      http://www.wikidata.org/entity/Q155018
1      http://www.wikidata.org/entity/Q640054
2      http://www.wikidata.org/entity/Q649656
3     http://www.wikidata.org/entity/Q1056781
4     http://www.wikidata.org/entity/Q1056912
..                                        ...
196   http://www.wikidata.org/entity/Q3792653
197   http://www.wikidata.org/entity/Q3927003
198  http://www.wikidata.org/entity/Q16876411
199  http://www.wikidata.org/entity/Q30602061
200  http://www.wikidata.org/entity/Q89265202

[201 rows x 1 columns]

In [38]:
based_on_italian_ww3 = """
SELECT DISTINCT ?derivativeWork
WHERE {
  {
    ?work wdt:P31 wd:Q47461344 .
  }UNION{
    ?work wdt:P31/wdt:P279* wd:Q7725634 .
  }
  ?derivativeWork wdt:P31/wdt:P279* wd:Q2431196  .
  ?derivativeWork wdt:P144 ?work .
                         
  ?country (wdt:P36 | p:P36 / ps:P36) ?capitalCity .  
  ?capitalCity wdt:P31 wd:Q515 ; #get cities
                  wdt:P17 wd:Q38 .

  ?work wdt:P495 ?country .
} 
"""
based_on_iww_df3 = query_wikidata(endpoint, based_on_italian_ww2, user_agent, True)

# Add the results to the set
for index, row in based_on_iww_df3.iterrows():
    derived_works_iww.add(row['derivativeWork'])

based_on_iww_df3

                               derivativeWork
0      http://www.wikidata.org/entity/Q155018
1      http://www.wikidata.org/entity/Q640054
2      http://www.wikidata.org/entity/Q649656
3     http://www.wikidata.org/entity/Q1056781
4     http://www.wikidata.org/entity/Q1056912
..                                        ...
196   http://www.wikidata.org/entity/Q3792653
197   http://www.wikidata.org/entity/Q3927003
198  http://www.wikidata.org/entity/Q16876411
199  http://www.wikidata.org/entity/Q30602061
200  http://www.wikidata.org/entity/Q89265202

[201 rows x 1 columns]

In [39]:
len(derived_works_iww)

261

## 2. Films and written works

In [49]:
derivative_works = set()
len(derivative_works)

0

In [50]:
q2_based_on = """
SELECT DISTINCT ?derivativeWork
WHERE {
  {
    ?work wdt:P31 wd:Q47461344 .
  }UNION{
    ?work wdt:P31/wdt:P279* wd:Q7725634 .
  }
  ?derivativeWork wdt:P31/wdt:P279* wd:Q11424  .
   ?derivativeWork wdt:P144 ?work .                           
} 
"""
based_on_df2 = query_wikidata(endpoint, q2_based_on, user_agent, True)

# Add the results to the set
for index, row in based_on_df2.iterrows():
    derivative_works.add(row['derivativeWork'])
    
based_on_df2

                                 derivativeWork
0          http://www.wikidata.org/entity/Q3589
1          http://www.wikidata.org/entity/Q4536
2         http://www.wikidata.org/entity/Q16458
3         http://www.wikidata.org/entity/Q23395
4         http://www.wikidata.org/entity/Q25069
...                                         ...
11315   http://www.wikidata.org/entity/Q7738172
11316  http://www.wikidata.org/entity/Q10339085
11317  http://www.wikidata.org/entity/Q10381445
11318  http://www.wikidata.org/entity/Q27964343
11319  http://www.wikidata.org/entity/Q57523564

[11320 rows x 1 columns]

In [51]:
q2_influenced_by = """
SELECT DISTINCT ?derivativeWork
WHERE {
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
    ?derivativeWork wdt:P31/wdt:P279* wd:Q11424  .
    ?derivativeWork wdt:P737 ?work .                           
} 
"""
influenced_by_df2 = query_wikidata(endpoint, q2_influenced_by, user_agent, True)

# Add the results to the set
for index, row in influenced_by_df2.iterrows():
    derivative_works.add(row['derivativeWork'])

influenced_by_df2

                            derivativeWork
0   http://www.wikidata.org/entity/Q337881
1   http://www.wikidata.org/entity/Q488655
2  http://www.wikidata.org/entity/Q1218888
3  http://www.wikidata.org/entity/Q3824799
4  http://www.wikidata.org/entity/Q4424338

In [52]:
q2_inspired_by = """
SELECT DISTINCT ?derivativeWork
WHERE {
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
    ?derivativeWork wdt:P31/wdt:P279* wd:Q11424  .
    ?derivativeWork wdt:P941 ?work .                           
} 
"""
inspired_by_df2 = query_wikidata(endpoint, q2_inspired_by, user_agent, True)

# Add the results to the set
for index, row in inspired_by_df2.iterrows():
    derivative_works.add(row['derivativeWork'])

inspired_by_df2

                               derivativeWork
0      http://www.wikidata.org/entity/Q189330
1     http://www.wikidata.org/entity/Q1196184
2     http://www.wikidata.org/entity/Q7728885
3      http://www.wikidata.org/entity/Q475763
4    http://www.wikidata.org/entity/Q16514601
..                                        ...
186   http://www.wikidata.org/entity/Q5285130
187   http://www.wikidata.org/entity/Q6651529
188  http://www.wikidata.org/entity/Q12125766
189  http://www.wikidata.org/entity/Q15865201
190   http://www.wikidata.org/entity/Q2027855

[191 rows x 1 columns]

In [53]:
q2_reference = """
SELECT DISTINCT ?derivativeWork
WHERE {
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
    ?derivativeWork wdt:P31/wdt:P279* wd:Q11424  .
    ?derivativeWork wdt:P8371 ?work .                           
} 
"""
reference_df2 = query_wikidata(endpoint, q2_reference, user_agent, True)

# Add the results to the set
for index, row in reference_df2.iterrows():
    derivative_works.add(row['derivativeWork'])

reference_df2

                               derivativeWork
0      http://www.wikidata.org/entity/Q327332
1      http://www.wikidata.org/entity/Q318975
2     http://www.wikidata.org/entity/Q1740171
3    http://www.wikidata.org/entity/Q11648811
4    http://www.wikidata.org/entity/Q16635326
5    http://www.wikidata.org/entity/Q22344480
6    http://www.wikidata.org/entity/Q65041276
7   http://www.wikidata.org/entity/Q100573244
8   http://www.wikidata.org/entity/Q107107865
9     http://www.wikidata.org/entity/Q8028590
10     http://www.wikidata.org/entity/Q147845
11     http://www.wikidata.org/entity/Q160560
12     http://www.wikidata.org/entity/Q182944
13     http://www.wikidata.org/entity/Q221236
14     http://www.wikidata.org/entity/Q250971
15     http://www.wikidata.org/entity/Q329805
16     http://www.wikidata.org/entity/Q466297
17     http://www.wikidata.org/entity/Q472600
18     http://www.wikidata.org/entity/Q579757
19    http://www.wikidata.org/entity/Q1066948
20    http://www.wikidata.org/entity/Q2554809
21    http://www.wikidata.org/entity/Q6418577
22   http://www.wikidata.org/entity/Q23817035
23   http://www.wikidata.org/entity/Q29567973
24   http://www.wikidata.org/entity/Q59488276
25   http://www.wikidata.org/entity/Q67171095
26   http://www.wikidata.org/entity/Q80322391
27   http://www.wikidata.org/entity/Q97168249
28  http://www.wikidata.org/entity/Q106097514
29  http://www.wikidata.org/entity/Q106371709
30      http://www.wikidata.org/entity/Q25366
31    http://www.wikidata.org/entity/Q2306760
32     http://www.wikidata.org/entity/Q535395
33    http://www.wikidata.org/entity/Q5690966
34   http://www.wikidata.org/entity/Q27918412
35     http://www.wikidata.org/entity/Q241218
36     http://www.wikidata.org/entity/Q200572
37   http://www.wikidata.org/entity/Q64577280
38    http://www.wikidata.org/entity/Q1689499

In [54]:
q2_derived = """
SELECT DISTINCT ?derivativeWork 
WHERE {
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
    ?derivativeWork wdt:P31/wdt:P279* wd:Q11424  .
    ?derivativeWork wdt:P4969 ?work .                           
} 
"""
derived_df2 = query_wikidata(endpoint, q2_derived, user_agent, True)

# Add the results to the set
for index, row in derived_df2.iterrows():
    derivative_works.add(row['derivativeWork'])

derived_df2

                                derivativeWork
0       http://www.wikidata.org/entity/Q204670
1       http://www.wikidata.org/entity/Q221103
2       http://www.wikidata.org/entity/Q171711
3       http://www.wikidata.org/entity/Q107940
4      http://www.wikidata.org/entity/Q1626245
..                                         ...
96    http://www.wikidata.org/entity/Q10882752
97    http://www.wikidata.org/entity/Q63104664
98   http://www.wikidata.org/entity/Q104630023
99   http://www.wikidata.org/entity/Q106707387
100  http://www.wikidata.org/entity/Q113539815

[101 rows x 1 columns]

In [55]:
q2_inspired_by_artist = """
SELECT DISTINCT ?derivativeWork
WHERE {
    {
      ?work wdt:P170 ?person .
     }UNION{
      ?work wdt:P50 ?person .                           
     }UNION{
      VALUES ?authorOf {wdt:P1455 wdt:P800}      
      ?person ?authorOf ?work .
    }
  
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
    
    ?derivativeWork wdt:P31/wdt:P279* wd:Q11424  .
    ?derivativeWork wdt:P1877 ?person .                                  
} 
"""
inspired_by_artist_df2 = query_wikidata(endpoint, q2_inspired_by_artist, user_agent, True)
inspired_by_artist_df2

                                 derivativeWork
0         http://www.wikidata.org/entity/Q45384
1        http://www.wikidata.org/entity/Q148326
2        http://www.wikidata.org/entity/Q151895
3        http://www.wikidata.org/entity/Q151923
4        http://www.wikidata.org/entity/Q151977
...                                         ...
5279  http://www.wikidata.org/entity/Q108046859
5280  http://www.wikidata.org/entity/Q110732121
5281  http://www.wikidata.org/entity/Q111528279
5282  http://www.wikidata.org/entity/Q112977213
5283  http://www.wikidata.org/entity/Q113676440

[5284 rows x 1 columns]

In [56]:
len(derivative_works)

11581

### b. Films and italian written works

In [57]:
derived_works_iww = set()

In [58]:
based_on_italian_ww = """
SELECT DISTINCT ?derivativeWork
WHERE {
  {
    ?work wdt:P31 wd:Q47461344 .
  }UNION{
    ?work wdt:P31/wdt:P279* wd:Q7725634 .
  }
  ?derivativeWork wdt:P31/wdt:P279* wd:Q11424  .
  ?derivativeWork wdt:P144 ?work .

  ?person wdt:P31 wd:Q5 ;
            wdt:P27 ?country .                          #the block gets the writers having had the citizenship of a country, whose capital city is now an Italian city
  ?country (wdt:P36 | p:P36 / ps:P36) ?capitalCity .  
  ?capitalCity wdt:P31 wd:Q515 ; #get cities
                  wdt:P17 wd:Q38 .


    {
      ?work wdt:P170 ?person .
     }UNION{
      ?work wdt:P50 ?person .                            
     }UNION{
      VALUES ?authorOf {wdt:P1455 wdt:P800}      
      ?person ?authorOf ?work .
    }

} 
"""
based_on_iww_df = query_wikidata(endpoint, based_on_italian_ww, user_agent, True)

# Add the results to the set
for index, row in based_on_iww_df.iterrows():
    derived_works_iww.add(row['derivativeWork'])

based_on_iww_df

                               derivativeWork
0       http://www.wikidata.org/entity/Q75593
1      http://www.wikidata.org/entity/Q128761
2      http://www.wikidata.org/entity/Q389511
3      http://www.wikidata.org/entity/Q578729
4      http://www.wikidata.org/entity/Q596623
..                                        ...
203  http://www.wikidata.org/entity/Q65047848
204   http://www.wikidata.org/entity/Q1199259
205  http://www.wikidata.org/entity/Q96376192
206  http://www.wikidata.org/entity/Q59348694
207   http://www.wikidata.org/entity/Q3950747

[208 rows x 1 columns]

In [59]:
based_on_italian_ww2 = """
SELECT DISTINCT ?derivativeWork
WHERE {
  {
    ?work wdt:P31 wd:Q47461344 .
  }UNION{
    ?work wdt:P31/wdt:P279* wd:Q7725634 .
  }
  ?derivativeWork wdt:P31/wdt:P279* wd:Q11424  .
  ?derivativeWork wdt:P144 ?work .
  
  ?work wdt:P407 wd:Q652 .
  
  MINUS {
     {
      ?work wdt:P170 ?person .
     }UNION{
      ?work wdt:P50 ?person .                            
     }UNION{
      VALUES ?authorOf {wdt:P1455 wdt:P800}      
      ?person ?authorOf ?work .
    }
  ?person wdt:P31 wd:Q5 ;
            wdt:P27 ?country .                          #the block gets the writers having had the citizenship of a country, whose capital city is now an Italian city
  ?country (wdt:P36 | p:P36 / ps:P36) ?capitalCity .  
  ?capitalCity wdt:P31 wd:Q515 . #get cities
  FILTER NOT EXISTS { ?capitalCity wdt:P17 wd:Q38 . }
  }

} 
"""
based_on_iww_df2 = query_wikidata(endpoint, based_on_italian_ww2, user_agent, True)

# Add the results to the set
for index, row in based_on_iww_df2.iterrows():
    derived_works_iww.add(row['derivativeWork'])

based_on_iww_df2

                               derivativeWork
0      http://www.wikidata.org/entity/Q155018
1      http://www.wikidata.org/entity/Q640054
2      http://www.wikidata.org/entity/Q649656
3      http://www.wikidata.org/entity/Q683014
4     http://www.wikidata.org/entity/Q1056781
..                                        ...
158   http://www.wikidata.org/entity/Q3704456
159   http://www.wikidata.org/entity/Q3791182
160   http://www.wikidata.org/entity/Q3792653
161   http://www.wikidata.org/entity/Q3927003
162  http://www.wikidata.org/entity/Q30602061

[163 rows x 1 columns]

In [60]:
based_on_italian_ww3 = """
SELECT DISTINCT ?derivativeWork
WHERE {
  {
    ?work wdt:P31 wd:Q47461344 .
  }UNION{
    ?work wdt:P31/wdt:P279* wd:Q7725634 .
  }
  ?derivativeWork wdt:P31/wdt:P279* wd:Q11424  .
  ?derivativeWork wdt:P144 ?work .
                         
  ?country (wdt:P36 | p:P36 / ps:P36) ?capitalCity .  
  ?capitalCity wdt:P31 wd:Q515 ; #get cities
                  wdt:P17 wd:Q38 .

  ?work wdt:P495 ?country .
} 
"""
based_on_iww_df3 = query_wikidata(endpoint, based_on_italian_ww2, user_agent, True)

# Add the results to the set
for index, row in based_on_iww_df3.iterrows():
    derived_works_iww.add(row['derivativeWork'])

based_on_iww_df3

                               derivativeWork
0      http://www.wikidata.org/entity/Q155018
1      http://www.wikidata.org/entity/Q640054
2      http://www.wikidata.org/entity/Q649656
3      http://www.wikidata.org/entity/Q683014
4     http://www.wikidata.org/entity/Q1056781
..                                        ...
158   http://www.wikidata.org/entity/Q3791182
159   http://www.wikidata.org/entity/Q3792653
160  http://www.wikidata.org/entity/Q19272577
161  http://www.wikidata.org/entity/Q24806853
162  http://www.wikidata.org/entity/Q30602061

[163 rows x 1 columns]

In [61]:
len(derived_works_iww)

215

## 3. For a comparison with written works and any kind of derivative

In [1]:
ww_ad_set = set()

In [5]:
q_ww_ad1 = """
SELECT DISTINCT ?derivativeWork
WHERE {
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }

    VALUES ?p {wdt:P737 wdt:P144 wdt:P941 wdt:P8371 wdt:P4969} 
      ?derivativeWork ?p ?work .                 
} 
"""

ww_ad_df1 = query_wikidata(endpoint, q_ww_ad1, user_agent, True)

# Add the results to the set
for index, row in ww_ad_df1.iterrows():
    ww_ad_set.add(row['derivativeWork'])

ww_ad_df1

                                  derivativeWork
0         http://www.wikidata.org/entity/Q130297
1         http://www.wikidata.org/entity/Q470572
2         http://www.wikidata.org/entity/Q649212
3         http://www.wikidata.org/entity/Q707986
4         http://www.wikidata.org/entity/Q821121
...                                          ...
26865  http://www.wikidata.org/entity/Q111813069
26866  http://www.wikidata.org/entity/Q107030825
26867    http://www.wikidata.org/entity/Q3511802
26868   http://www.wikidata.org/entity/Q55431672
26869   http://www.wikidata.org/entity/Q16761304

[26870 rows x 1 columns]

In [6]:
q_ww_ad2 = """
SELECT DISTINCT ?derivativeWork
WHERE {
    {
      ?work wdt:P170 ?creator .
     }UNION{
      ?work wdt:P50 ?creator .                       
     }UNION{
      VALUES ?authorOf {wdt:P1455 wdt:P800}      
      ?creator ?authorOf ?work .
    }
    {
      ?work wdt:P31 wd:Q47461344 .
    }UNION{
      ?work wdt:P31/wdt:P279* wd:Q7725634 .
    }
      ?derivativeWork wdt:P1877 ?creator .
                        
} 
"""

ww_ad_df2 = query_wikidata(endpoint, q_ww_ad2, user_agent, True)

# Add the results to the set
for index, row in ww_ad_df2.iterrows():
    ww_ad_set.add(row['derivativeWork'])

ww_ad_df2

                                derivativeWork
0      http://www.wikidata.org/entity/Q1056781
1     http://www.wikidata.org/entity/Q57449255
2     http://www.wikidata.org/entity/Q57449284
3     http://www.wikidata.org/entity/Q57449300
4     http://www.wikidata.org/entity/Q57449311
...                                        ...
8107  http://www.wikidata.org/entity/Q57512723
8108    http://www.wikidata.org/entity/Q217189
8109  http://www.wikidata.org/entity/Q57503536
8110  http://www.wikidata.org/entity/Q57506879
8111     http://www.wikidata.org/entity/Q19069

[8112 rows x 1 columns]

In [7]:
len(ww_ad_set)

29936